/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stream_request_service;

import akka.NotUsed;

import akka.actor.ActorSystem;

import akka.http.javadsl.ConnectHttp;
import akka.http.javadsl.Http; 
import akka.http.javadsl.ServerBinding; 
import akka.http.javadsl.model.HttpRequest; 
import akka.http.javadsl.model.HttpResponse;

import akka.stream.ActorMaterializer; 
import akka.stream.javadsl.Flow;

import io.vavr.control.Option;

import java.util.concurrent.CompletionStage;
import java.io.IOException;
import java.net.InetSocketAddress;

import stream_request_service.rest.ClientApi;

public final class App {

    private static final String domain = "0.0.0.0";
    private static final int port = 8080;

    public static void main(String[] args) throws IOException {
        final ActorSystem system = ActorSystem.create("stream-request-server");
        final ActorMaterializer materializer = ActorMaterializer.create(system);
        final Http http = Http.get(system);

        ClientApi clientApi = new ClientApi(system, materializer);

        final Flow<HttpRequest, HttpResponse,NotUsed> routeFlow = clientApi.createRoute().flow(system, materializer);

        System.out.println("Server is online !!!!!");
        final CompletionStage<ServerBinding> futureBinding = http.bindAndHandle (
            routeFlow,
            ConnectHttp.toHost(domain, port),
            materializer
        );
    }
}
