# Generated by Django 3.1.3 on 2021-11-01 13:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211101_1225'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='products',
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
