# Generated by Django 3.1.3 on 2021-11-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211101_1319'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='products',
            managers=[
            ],
        ),
    ]
