server:
  port: 8011

incomingEvent:
  avroPublishRatingEvent: AvroPublishRatingEvent
  avroUpdateRatingEvent: AvroUpdateRatingEvent
  avroDeleteRatingEvent: AvroDeleteRatingEvent

transactionKafka:
  messageId: 1
  bootstrapServers: ${KAFKA_INTERNAL_HOST}:9092
  transactionIdPrefix: ratingCommand
  topic: ${TOPIC_NAME}

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST}:${REGISTRY_PORT}/eureka/
  instance:
    appname: command-rating-service
    preferIpAddress: true