server:
  port: 0

incomingEvent:
  avroPublishRatingEvent: AvroPublishRatingEvent
  avroUpdateRatingEvent: AvroUpdateRatingEvent
  avroDeleteRatingEvent: AvroDeleteRatingEvent

transactionKafka:
  messageId: 1
  bootstrapServers: kafka:9092
  transactionIdPrefix: ratingCommand
  topic: ratingCommandToEventSource

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: command-rating-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
    prefer-ip-address: true

ribbon:
  eureka:
    enabled: true