server:
  port: 8011

incomingEvent:
  avroPublishRatingEvent: AvroPublishRatingEvent
  avroUpdateRatingEvent: AvroUpdateRatingEvent
  avroDeleteRatingEvent: AvroDeleteRatingEvent

transactionKafka:
  messageId: 1
  bootstrapServers: ${KAFKA_INTERNAL_HOST}:9092
  transactionIdPrefix: ratingCommand
  topic: ${TOPIC_NAME}
