"""empty message

Revision ID: 1e87f79eb413
Revises: e7b2bbd91ed6
Create Date: 2021-11-01 10:58:53.764905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e87f79eb413'
down_revision = 'e7b2bbd91ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_change_histroy', 'action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_change_histroy', sa.Column('action', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
