server:
  port: 8001

#Postgre setup 
spring.datasource:
  url: jdbc:postgresql://postgresql:5432/EventSource
  username: postgres
  password: password
  initialization-mode: always

DBTable:
  clientIdCol: clientId
  itemIdCol: itemId
  scoreCol: score
  eventTypeCol: eventType

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

redis:
  host: redis
  port: 6379
  expireTime: 300

incomingEvent:
  avroPublishRatingEvent: AvroPublishRatingEvent
  avroUpdateRatingEvent: AvroUpdateRatingEvent
  avroDeleteRatingEvent: AvroDeleteRatingEvent

ConsumerKafka:
  bootstrapServers: kafka:9092
  groupId: eventSourcing
  topicConsumerFromRatingCommand: ratingCommandToEventSource

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    appname: event-source-storage
    preferIpAddress: true
