server:
  port: 8001

#Postgre setup 
spring.datasource:
  url: jdbc:postgresql://postgresql:5432/EventSource
  username: postgres
  password: password

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  expireTime: ${REDIS_LIFE_TIME}

incomingEvent:
  avroPublishRatingEvent: AvroPublishRatingEvent
  avroUpdateRatingEvent: AvroUpdateRatingEvent
  avroDeleteRatingEvent: AvroDeleteRatingEvent

ConsumerKafka:
  bootstrapServers: ${KAFKA_INTERNAL_HOST}:9092
  groupId: ${CONSUMER_GROUP}
  topicConsumerFromRatingCommand: ${TOPIC_NAME}
