server:
  port: 8001

incomingEvent:
  avroPublishRatingEvent: AvroPublishRatingEvent
  avroUpdateRatingEvent: AvroUpdateRatingEvent
  avroDeleteRatingEvent: AvroDeleteRatingEvent

ConsumerKafka:
  bootstrapServers: ${KAFKA_INTERNAL_HOST}:9092
  groupId: ${CONSUMER_GROUP}
  topicConsumerFromRatingCommand: ${TOPIC_NAME}
