server:
  port: 8001

#Postgre setup 
spring.datasource:
  url: jdbc:postgresql://postgresql:5432/EventSource
  username: postgres
  password: password
  initialization-mode: always

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  expireTime: ${REDIS_LIFE_TIME}

incomingEvent:
  avroPublishRatingEvent: AvroPublishRatingEvent
  avroUpdateRatingEvent: AvroUpdateRatingEvent
  avroDeleteRatingEvent: AvroDeleteRatingEvent

ConsumerKafka:
  bootstrapServers: ${KAFKA_INTERNAL_HOST}:9092
  groupId: ${CONSUMER_GROUP}
  topicConsumerFromRatingCommand: ${TOPIC_NAME}
