server:
  port: 8761
  
eureka:
  instance:
    hostname: ${HOST_NAME}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/