server:
  port: 8761

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  
eureka:
  instance:
    hostname: serviceregistry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/