topic:
  name: words-from-client 
  partitions-num: 10 
  replication-factor: 3
spring:
  kafka:
    bootstrap-servers:
      - ${BROKER_HOST}:${BROKER_PORT}
    producer:
      keySerializer: org.springframework.kafka.support.serializer.JsonSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer