/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package vn.datnguyen.recommender.AvroClasses;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroRecommendForUser extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5539006513431343326L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroRecommendForUser\",\"namespace\":\"vn.datnguyen.recommender.AvroClasses\",\"fields\":[{\"name\":\"clientId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"limit\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String clientId;
  @Deprecated public int limit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroRecommendForUser() {}

  /**
   * All-args constructor.
   * @param clientId The new value for clientId
   * @param limit The new value for limit
   */
  public AvroRecommendForUser(java.lang.String clientId, java.lang.Integer limit) {
    this.clientId = clientId;
    this.limit = limit;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return clientId;
    case 1: return limit;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: clientId = (java.lang.String)value$; break;
    case 1: limit = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'clientId' field.
   * @return The value of the 'clientId' field.
   */
  public java.lang.String getClientId() {
    return clientId;
  }

  /**
   * Sets the value of the 'clientId' field.
   * @param value the value to set.
   */
  public void setClientId(java.lang.String value) {
    this.clientId = value;
  }

  /**
   * Gets the value of the 'limit' field.
   * @return The value of the 'limit' field.
   */
  public java.lang.Integer getLimit() {
    return limit;
  }

  /**
   * Sets the value of the 'limit' field.
   * @param value the value to set.
   */
  public void setLimit(java.lang.Integer value) {
    this.limit = value;
  }

  /**
   * Creates a new AvroRecommendForUser RecordBuilder.
   * @return A new AvroRecommendForUser RecordBuilder
   */
  public static vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder newBuilder() {
    return new vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder();
  }

  /**
   * Creates a new AvroRecommendForUser RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroRecommendForUser RecordBuilder
   */
  public static vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder newBuilder(vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder other) {
    return new vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder(other);
  }

  /**
   * Creates a new AvroRecommendForUser RecordBuilder by copying an existing AvroRecommendForUser instance.
   * @param other The existing instance to copy.
   * @return A new AvroRecommendForUser RecordBuilder
   */
  public static vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder newBuilder(vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser other) {
    return new vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder(other);
  }

  /**
   * RecordBuilder for AvroRecommendForUser instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroRecommendForUser>
    implements org.apache.avro.data.RecordBuilder<AvroRecommendForUser> {

    private java.lang.String clientId;
    private int limit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.limit)) {
        this.limit = data().deepCopy(fields()[1].schema(), other.limit);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroRecommendForUser instance
     * @param other The existing instance to copy.
     */
    private Builder(vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.clientId)) {
        this.clientId = data().deepCopy(fields()[0].schema(), other.clientId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.limit)) {
        this.limit = data().deepCopy(fields()[1].schema(), other.limit);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'clientId' field.
      * @return The value.
      */
    public java.lang.String getClientId() {
      return clientId;
    }

    /**
      * Sets the value of the 'clientId' field.
      * @param value The value of 'clientId'.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder setClientId(java.lang.String value) {
      validate(fields()[0], value);
      this.clientId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'clientId' field has been set.
      * @return True if the 'clientId' field has been set, false otherwise.
      */
    public boolean hasClientId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'clientId' field.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder clearClientId() {
      clientId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'limit' field.
      * @return The value.
      */
    public java.lang.Integer getLimit() {
      return limit;
    }

    /**
      * Sets the value of the 'limit' field.
      * @param value The value of 'limit'.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder setLimit(int value) {
      validate(fields()[1], value);
      this.limit = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'limit' field has been set.
      * @return True if the 'limit' field has been set, false otherwise.
      */
    public boolean hasLimit() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'limit' field.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.AvroRecommendForUser.Builder clearLimit() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public AvroRecommendForUser build() {
      try {
        AvroRecommendForUser record = new AvroRecommendForUser();
        record.clientId = fieldSetFlags()[0] ? this.clientId : (java.lang.String) defaultValue(fields()[0]);
        record.limit = fieldSetFlags()[1] ? this.limit : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
