/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package vn.datnguyen.recommender.AvroClasses;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RecommendItemSimilaritesResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5074652942563432957L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RecommendItemSimilaritesResult\",\"namespace\":\"vn.datnguyen.recommender.AvroClasses\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"timestamp\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"SimilarItems\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Item\",\"fields\":[{\"name\":\"itemId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"difference\",\"type\":\"double\"}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String id;
  @Deprecated public java.lang.String timestamp;
  @Deprecated public java.util.List<vn.datnguyen.recommender.AvroClasses.Item> SimilarItems;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RecommendItemSimilaritesResult() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param timestamp The new value for timestamp
   * @param SimilarItems The new value for SimilarItems
   */
  public RecommendItemSimilaritesResult(java.lang.String id, java.lang.String timestamp, java.util.List<vn.datnguyen.recommender.AvroClasses.Item> SimilarItems) {
    this.id = id;
    this.timestamp = timestamp;
    this.SimilarItems = SimilarItems;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return timestamp;
    case 2: return SimilarItems;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: timestamp = (java.lang.String)value$; break;
    case 2: SimilarItems = (java.util.List<vn.datnguyen.recommender.AvroClasses.Item>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.String getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.String value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'SimilarItems' field.
   * @return The value of the 'SimilarItems' field.
   */
  public java.util.List<vn.datnguyen.recommender.AvroClasses.Item> getSimilarItems() {
    return SimilarItems;
  }

  /**
   * Sets the value of the 'SimilarItems' field.
   * @param value the value to set.
   */
  public void setSimilarItems(java.util.List<vn.datnguyen.recommender.AvroClasses.Item> value) {
    this.SimilarItems = value;
  }

  /**
   * Creates a new RecommendItemSimilaritesResult RecordBuilder.
   * @return A new RecommendItemSimilaritesResult RecordBuilder
   */
  public static vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder newBuilder() {
    return new vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder();
  }

  /**
   * Creates a new RecommendItemSimilaritesResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RecommendItemSimilaritesResult RecordBuilder
   */
  public static vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder newBuilder(vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder other) {
    return new vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder(other);
  }

  /**
   * Creates a new RecommendItemSimilaritesResult RecordBuilder by copying an existing RecommendItemSimilaritesResult instance.
   * @param other The existing instance to copy.
   * @return A new RecommendItemSimilaritesResult RecordBuilder
   */
  public static vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder newBuilder(vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult other) {
    return new vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder(other);
  }

  /**
   * RecordBuilder for RecommendItemSimilaritesResult instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RecommendItemSimilaritesResult>
    implements org.apache.avro.data.RecordBuilder<RecommendItemSimilaritesResult> {

    private java.lang.String id;
    private java.lang.String timestamp;
    private java.util.List<vn.datnguyen.recommender.AvroClasses.Item> SimilarItems;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.SimilarItems)) {
        this.SimilarItems = data().deepCopy(fields()[2].schema(), other.SimilarItems);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RecommendItemSimilaritesResult instance
     * @param other The existing instance to copy.
     */
    private Builder(vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[1].schema(), other.timestamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.SimilarItems)) {
        this.SimilarItems = data().deepCopy(fields()[2].schema(), other.SimilarItems);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.String getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder setTimestamp(java.lang.String value) {
      validate(fields()[1], value);
      this.timestamp = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder clearTimestamp() {
      timestamp = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'SimilarItems' field.
      * @return The value.
      */
    public java.util.List<vn.datnguyen.recommender.AvroClasses.Item> getSimilarItems() {
      return SimilarItems;
    }

    /**
      * Sets the value of the 'SimilarItems' field.
      * @param value The value of 'SimilarItems'.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder setSimilarItems(java.util.List<vn.datnguyen.recommender.AvroClasses.Item> value) {
      validate(fields()[2], value);
      this.SimilarItems = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'SimilarItems' field has been set.
      * @return True if the 'SimilarItems' field has been set, false otherwise.
      */
    public boolean hasSimilarItems() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'SimilarItems' field.
      * @return This builder.
      */
    public vn.datnguyen.recommender.AvroClasses.RecommendItemSimilaritesResult.Builder clearSimilarItems() {
      SimilarItems = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public RecommendItemSimilaritesResult build() {
      try {
        RecommendItemSimilaritesResult record = new RecommendItemSimilaritesResult();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.timestamp = fieldSetFlags()[1] ? this.timestamp : (java.lang.String) defaultValue(fields()[1]);
        record.SimilarItems = fieldSetFlags()[2] ? this.SimilarItems : (java.util.List<vn.datnguyen.recommender.AvroClasses.Item>) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
