server:
  port: 8002

DBTable:
  clientIdCol: clientId
  itemIdCol: itemId
  scoreCol: score
  eventTypeCol: eventType

incomingEvent:
  avroPublishRatingEvent: AvroPublishRatingEvent
  avroUpdateRatingEvent: AvroUpdateRatingEvent
  avroDeleteRatingEvent: AvroDeleteRatingEvent

transactionKafka:
  messageId: 1
  bootstrapServers: kafka:9092
  transactionIdPrefix: fromEventSource
  topicToQueryService: ratingCommandFromEventSource
  topicToRecommendSerivce: ratingCommandForRecommendation

#Postgre setup 
spring.datasource:
  url: jdbc:postgresql://postgresql:5432/EventSource
  username: postgres
  password: password
  initialization-mode: always

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    appname: wal-tailing-service
    preferIpAddress: true