version: '3.8'
services:
  backend:
    build:
      context: . 
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:7000'
    ports:
      - 7000:7000
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: user_view
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306