server:
  port: 8765

services:
  queryRating: lb://QUERY-RATING-SERVICE
  commandRating: lb://COMMAND-RATING-SERVICE

spring:
  application:
    name: api-gateway

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
    prefer-ip-address: true
