server:
  port: 8765

services:
  queryRating: lb://QUERY-RATING-SERVICE
  commandRating: lb://COMMAND-RATING-SERVICE

spring:
  application:
    name: api-gateway 
  cloud:
    discovery:
      enabled: true 
      client:
        health-indicator:
          enabled: true 
    gateway:
      discovery:
        locator:
          enabled: true

management:
  security:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
    prefer-ip-address: true
