/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package payment_processor;

import akka.actor.ActorSystem;

import akka.stream.ActorMaterializer;

import payment_processor.stream.KafkaConsumer;

public class App {
    public static void main(String[] args) {
        final ActorSystem system = ActorSystem.create("payment-gateway-service");
        final ActorMaterializer materializer = ActorMaterializer.create(system);

        KafkaConsumer kafkaConsumer = new KafkaConsumer(system, materializer);

        System.out.println(kafkaConsumer.getName());

        System.out.println("Payment gateway start !!!");
    }
}
