/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package payment_processor;

import akka.Done;
import akka.actor.ActorSystem;

import akka.stream.ActorMaterializer;

import java.util.concurrent.CompletionStage;
import payment_processor.stream.KafkaConsumer;

public class App {
    public static void main(String[] args) {
        final ActorSystem system = ActorSystem.create("payment-gateway-service");
        final ActorMaterializer materializer = ActorMaterializer.create(system);

        KafkaConsumer kafkaConsumer = new KafkaConsumer(system, materializer);

        System.out.println(kafkaConsumer.getName());

        final CompletionStage<Done> gateway = kafkaConsumer.consume();

        gateway.whenComplete((done,ex) -> system.terminate());
        
    }
}
