# Generated by Django 3.2.8 on 2021-10-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_store', '0003_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-date_created',), 'verbose_name_plural': 'products'},
        ),
    ]
