version: '3.8'
services:

## Registry services
  serviceregistry:
    container_name: service-registry
    build: 
      context: ./service-registry
    ports:
      - 8761:8761 
    volumes:
      - ./service-registry/target/service-registry-1.0-SNAPSHOT.jar:/recommender/service-registry.jar
    command: "java -Xmx256m -jar /recommender/service-registry.jar"
    
## RATING COMMAND 
  commandrating:
    build: 
      context: ./command-rating-service
    depends_on:
      - kafka
      - serviceregistry
    #ports:
    #  - "7000:2222"
    volumes:
      - ./command-rating-service/target/command-rating-service-1.0-SNAPSHOT.jar:/recommender/command-rating-service.jar
    command: "java -Xmx256m -jar /recommender/command-rating-service.jar"

## Query service  
  queryrating:
    build: 
      context: ./query-rating-service
    depends_on:
      - kafka
      - dynamodb
      - serviceregistry
    #ports:
    #  - "7001:2222"
    volumes:
      - ./query-rating-service/target/query-rating-service-1.0-SNAPSHOT.jar:/recommender/query-rating-service.jar
    command: "java -Xmx256m -jar /recommender/query-rating-service.jar"

## EVENT SOURCE STORAGE 
  eventstorage:
    container_name: event-source-storage
    build:
      context: ./event-source-storage
    depends_on:
      - kafka
      - redis
      - postgresql
      - serviceregistry
    #ports:
    #  - 2222
    volumes:
      - ./event-source-storage/target/event-source-storage-1.0-SNAPSHOT.jar:/recommender/event-source-storage.jar
    command: "java -Xmx256m -jar /recommender/event-source-storage.jar"
  
  walminer:
    container_name: wal-miner
    build: 
      context: ./transaction-log-tailling
    depends_on:
      - postgresql
      - eventstorage
      - serviceregistry
    #ports:
    #  - 2222
    volumes:
      - ./transaction-log-tailling/target/transaction-log-tailling-1.0-SNAPSHOT.jar:/recommender/transaction-log-tailling.jar
    command: "java -Xmx256m -jar /recommender/transaction-log-tailling.jar"

## API GATEWAY
  apigateway:
    container_name: api-gateway
    build: 
      context: ./api-gateway
    ports:
      - 8765:8765
    depends_on:
      - serviceregistry
    volumes:
      - ./api-gateway/target/api-gateway-1.0-SNAPSHOT.jar:/recommender/api-gateway.jar
    command: "java -Xmx256m -jar /recommender/api-gateway.jar"

  recommenderrealtimeservice:
    image: storm:1.2.4
    container_name: recommender-real-time-service
    depends_on:
      - nimbus
      - kafka 
      - redis
    volumes:
      - ./recommender-real-time-service/target:/topology-definition
      - ./recommender-real-time-service/deployment:/topology-deployment
    command: /topology-deployment/deploy-topology.sh

  testingrating:
    build: 
      context: ./test-recommender-api
    depends_on:
      - kafka
    ports:
      - "3456:3456"
    volumes:
      - ./test-recommender-api/target/test-recommender-api-1.0-SNAPSHOT.jar:/recommender/test-recommender-api.jar
    command: "java -Xmx256m -jar /recommender/test-recommender-api.jar"