version: "3"
services:
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      CLUSTER_NAME: "local-distributed-test"
    env_file:
      - ./hadoop-env/hadoop.env
    ports:
      - 50070:50070
  
  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop-env/hadoop.env
    ports:
      - 50075:50075
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:latest
    container_name: resourcemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop-env/hadoop.env
    ports:
      - 8088:8088
  
  nodemanager:
    image: bde2020/hadoop-nodemanager:latest
    container_name: nodemanager
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop-env/hadoop.env
    ports:
      - 8042:8042

  historyserver:
    image: bde2020/hadoop-historyserver:latest
    container_name: historyserver
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop-env/hadoop.env
    ports:
      - 8188:8188

  hbase-master:
    image: bde2020/hbase-master:latest
    container_name: hbase-master
    hostname: hbase-master
    env_file:
      - ./hadoop/hbase-local-distributed.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181"
    ports:
      - 16010:16010
  
  hbase-region:
    image: bde2020/hbase-regionserver:latest
    container_name: hbase-regionserver
    hostname: hbase-regionserver
    env_file:
      - ./hadoop/hbase-local-distributed.env
    environment:
      HBASE_CONF_hbase_regionserver_hostname: hbase-region
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 zookeeper:2181 hbase-master:16010"
    ports:
      - 16030:16030

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver: