version: '3.8'
services:
## RATING COMMAND 
  ratingcommand:
    container_name: rating-command-service 
    build: 
      context: ./rating-command-service
    ports:
      - 8000:8000
    environment:
      SERVICE_PORT: 8000