version: '3.8'
services:
## RATING COMMAND 
  commandrating:
    container_name: command-rating-service
    build: 
      context: ./command-rating-service
    ports:
      - 8000:8000
    volumes:
      - ./command-rating-service/target/command-rating-service-1.0-SNAPSHOT.jar:/recommender/command-rating-service.jar
    environment:
      SERVICE_PORT: 8000
    command: "java -Xmx256m -jar /recommender/command-rating-service.jar"