version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    hostname: zookeeper 
    container_name: zookeeper 
    ports:
      - "2181:2181"  
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: wurstmeister/kafka:latest
    hostname: kafka 
    container_name: kafka 
    depends_on:
      - zookeeper 
    ports:
      - "9092:9092" 
    expose:
      - "9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  redis:
    container_name: redis
    image: redis:6.0.6
    ports:
      - "6379:6379"
  
  postgresql:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: EventSource

## RATING COMMAND 
  commandrating:
    container_name: command-rating-service
    build: 
      context: ./command-rating-service
    ports:
      - 8000:8000
    depends_on:
      - kafka
    volumes:
      - ./command-rating-service/target/command-rating-service-1.0-SNAPSHOT.jar:/recommender/command-rating-service.jar
    environment:
      KAFKA_INTERNAL_HOST: kafka
      TOPIC_NAME: ratingCommandToEventSource
    command: "java -Xmx256m -jar /recommender/command-rating-service.jar"

## EVENT SOURCE STORAGE 
  eventstorage:
    container_name: event-source-storage
    build:
      context: ./event-source-storage
    ports:
      - 8001:8001 
    depends_on:
      - kafka
      - redis
      - postgresql
    volumes:
      - ./event-source-storage/target/event-source-storage-1.0-SNAPSHOT.jar:/recommender/event-source-storage.jar
    environment:
      KAFKA_INTERNAL_HOST: kafka
      TOPIC_NAME: ratingCommandToEventSource
      CONSUMER_GROUP: eventSourcing
      REDIS_HOST: redis 
      REDIS_PORT: 6379
      REDIS_LIFE_TIME: 300
    command: "java -Xmx256m -jar /recommender/event-source-storage.jar"
