version: '3.8'
services:

## LOCAL EVENTUATE
  zookeeper:
    image: eventuateio/eventuateio-local-zookeeper:0.9.0
    ports:
      - 2181:2181 
      - 2888:2888
      - 3888:3888

  kafka:
    image: eventuateio/eventuateio-local-kafka:0.9.0
    ports:
      - 9092:9092 
    depends_on:
      - zookeeper
    expose:
      - 9093
    environment:
      KAFKA_BROKER_ID: 1
      ZOOKEEPER_SERVERS: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  mysql:
    image: eventuateio/eventuateio-local-mysql:0.9.0
    ports:
      - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_USER: datng 
      MYSQL_PASSWORD: datngpw

  cdcservice:
    image: eventuateio/eventuateio-local-cdc-service:0.9.0 
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka 
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: datng
      SPRING_DATASOURCE_PASSWORD: datngpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpw

## RATING COMMAND 
  rating-command:
    container_name: rating-command-service 
    build: 
      context: ./rating-command-service
    depends_on:
      - mysql 
      - kafka 
      - zookeeper
    ports:
      - 8000:8000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: datng
      SPRING_DATASOURCE_PASSWORD: datngpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpw
      SERVICE_PORT: 8000