version: '3.8'
services:
## RATING COMMAND 
  commandrating:
    container_name: command-rating-service
    build: 
      context: ./command-rating-service
    ports:
      - 8000:8000
    environment:
      SERVICE_PORT: 8000