name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker container in Test environment
      working-directory: ./services/recommender_service
      run: docker-compose -f docker-compose-test-recommender.yml up -d --scale supervisor=1
