server:
  port: 0

ConsumerKafka:
  bootstrapServers: kafka:9092
  groupId: fromEventSourcing
  topicConsumerFromEventSource: ratingCommandFromEventSource

amazon:
  dynamodb:
    endpoint: http://dynamodb:8000
  aws:
    accesskey: aws-access-key
    secretkey: aws-secret-key

spring:
  application:
    name: query-rating-service

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://serviceregistry:8761/eureka/
  instance:
    prefer-ip-address: true
    
ribbon:
  eureka:
    enabled: true