server:
  port: 8010

amazon:
  dynamodb:
    #endpoint: https://localhost:8000
    endpoint: htpp://${DYNAMODB_HOST}:${DYNAMODB_PORT}
  aws:
    accesskey: aws-access-key
    secretkey: aws-secret-key