server:
  port: 8010

ConsumerKafka:
  bootstrapServers: ${KAFKA_INTERNAL_HOST}:9092
  groupId: ${CONSUMER_GROUP}
  topicConsumerFromEventSource: ${TOPIC_NAME}

amazon:
  dynamodb:
    endpoint: http://${DYNAMODB_HOST}:${DYNAMODB_PORT}
  aws:
    accesskey: aws-access-key
    secretkey: aws-secret-key

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST}:${REGISTRY_PORT}/eureka/
  instance:
    appname: query-rating-service
    preferIpAddress: true