server:
  port: 0

redis:
  host: redis
  port: 6379
  expireTime: 300

ConsumerKafka:
  bootstrapServers: kafka:9092
  groupId: fromEventSourcing
  topicConsumerFromEventSource: ratingCommandFromEventSource

amazon:
  dynamodb:
    endpoint: http://dynamodb:8000
  aws:
    accesskey: aws-access-key
    secretkey: aws-secret-key

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true 
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    appname: query-rating-service
    preferIpAddress: true